### ISSUE TITLE
(0.) Mike(bug because of functionality) Because ... Rebuilt a built project... repo already exists... causes issue. 

### ISSUE THREAD

**Issue by MichaelDimmitt** [murjax/Github-Repo-Submodulizer#22]

**Comment by MichaelDimmitt** [comment]
@murjax do you get this error on your environment?

**Comment by murjax** [comment]
I believe it was resolved a couple of commits ago. I received a similar error when running test_delete_all, The problem seems to have originated inside sub_folder_level where it was attempting to call removeFiles_addSubmodule followed by commit_andPush on a no longer existing remote repo.  My test environment runs correctly. 

<b>-a note from mike:</b>
This is not the case ... explained in updated comment at top.
if you run:
rake test_submodulize_folder
rake test_submodulize_folder
rake test_delete_all

The issue will be recreated.

**Comment by MichaelDimmitt** [comment]
Possibly was resolved with:  'git push --quiet'.

**Comment by MichaelDimmitt** [comment]
did not have readme ... problem with one repository. "1_test_CheckReadmeAndSubdirs"

**Comment by MichaelDimmitt** [comment]
The issue turned out to be ... clone was not recursive. 
This issue is finished with 89f2f674b438373b9dfd6305a866398639aafe08

**Comment by MichaelDimmitt** [comment]
still an issue... a particular submodule not working.
<br>(1)if you run: ‘test_initialize_submodule twice’
<br>(2)then ‘test_delete_all’
<br>(3) once again ‘test_initialize_submodule’
<br>(4) check 1_test_CheckReadmeAndSubdirs it will have a submodule… when you click it 404
